INPUT_RESOLUTION = 640
FRAME_SKIP = 1
CONFIDENCE = 0.31

YOUTUBE_URL = "https://www.youtube.com/watch?v=0dKNLFFcHFU"
DURATION = 60
TARGET_FPS = 30

CLASS_NAMES = {
    2: "vehicle",
    3: "vehicle",
    5: "vehicle",
    7: "vehicle"
}

SPANISH_NAMES = {
    "vehicle": "vehiculo"
}

VEHICLE_CLASSES = [2, 3, 5, 7]

IOU_THRESHOLD = 0.15
OVERLAP_THRESHOLD = 0.4
DISAPPEAR_THRESHOLD = 40
COOLDOWN_FRAMES = 8
MIN_CONSECUTIVE_DETECTIONS = 1
MAX_PREDICTION_FRAMES = 15
CLASS_HISTORY_SIZE = 5

ROI_ENABLED = True
ROI_COORDS = [0.8, 0.63, 1.0, 0.85]
ROI_COLOR = (0, 255, 0)
ROI_THICKNESS = 2
